version: '3'
services:
  nodered:
    container_name: timelapse
    restart: always
    image: nodered/node-red
    user: '0'    
    ports:
      - '9008:1880'
    volumes:
      - ./nodered:/data
      - ./recordings:/recordings
    environment:
      - TZ=Europe/Stockholm
